### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by sanjusare** [niemasd/ViralMSA#13]
I was trying to use your ViralMSA.py program, but when I tried to run I got a message of that my .sam file is not found

I am attaching a text of the error message and the reference file and a file of sequences, if you can help me I will be very grateful.

Thank you very much in advance,

[error.zip](https://github.com/niemasd/ViralMSA/files/5638944/error.zip)
[error.zip](https://github.com/niemasd/ViralMSA/files/5638945/error.zip)

**Comment by niemasd** [comment]
I was unable to replicate the error on my end: ViralMSA ran to completion, and the multiple sequence alignment it output seemed fine. Here is the output folder, including the log file:

[output.zip](https://github.com/niemasd/ViralMSA/files/5639113/output.zip)

Are you sure `minimap2` is working properly on your system?

**Comment by sanjusare** [comment]
seems that I have to tested the installation of minimap.

Do you have any form or example data to test the minimap in my pc
independently to ViralMSA?

Thank you very much in advance

**Comment by niemasd** [comment]
I would recommend referring to the Minimap2 documentation for instructions on how to install:

https://github.com/lh3/minimap2#install

**Comment by niemasd** [comment]
It sounds like you may have resolved the issue, so I will go ahead and close this Issue, but please feel free to reopen it if you still have the same issue

**Comment by sanjusare** [comment]
Yes I solved it, I was working with Minimap version 2.13 compiled with foss
(213-foss-2018b) and did not function,but when I used the version compiled
with GCC (2.17-GCCcore-9.3.0) it functions very well.
Thank you very much for your assitance

**Comment by niemasd** [comment]
No problem at all; I'm glad to hear you were able to get things running 😄
