### ISSUE TITLE
Minimap2 is not runnable in your PATH?

### ISSUE THREAD

**Issue by BEAST-Community** [niemasd/ViralMSA#20]
(base) lixingguangtekiMacBook-puro:ViralMSA-Demo-VEME-2021-main lixingguang$ ViralMSA.py -e xingguanglee@hotmail.com -r SARS-CoV-2 -o viralmsa_output -s andersen_consensus_2021-08-28.fasta
ERROR: Minimap2 is not runnable in your PATH

**Comment by niemasd** [comment]
Thanks for reaching out! According to the error message, it seems as though Minimap2 may not be installed on your machine. Can you try installing Minimap2 and then try again?

**Comment by BEAST-Community** [comment]
thanks, i will try it.

**Comment by niemasd** [comment]
Sounds good! I'll go ahead and close this Issue because installing Minimap2 in your `PATH` should resolve this, but if you have any other errors, feel free to follow up with a new Issue
