### ISSUE TITLE
wfmash cite

### ISSUE THREAD

**Issue by ekg** [niemasd/ViralMSA#23]
Thanks for integrating wfmash. I'm curious how your experience with it goes so please reach out. Would be happy to chat as I'm also working with virus populations. 

I'm writing here b/c of a silly technical thing. If you use the base-level (default alignment with cigar) in your approach please also cite:

> Santiago Marco-Sola, Juan Carlos Moure, Miquel Moreto, and Antonio Espinosa "Fast gap-affine pairwise alignment using the wavefront algorithm" Bioinformatics, 2020.

`wfmash -m` is roughly equivalent to Mashmap2 with a length filter on the alignments. If you just use that then sorry for the noise!

We are working on a wfmash manuscript, and we plan to post in the coming months, but the core ideas are first worked out in both of these papers. 

Cheers!

**Comment by niemasd** [comment]
Thanks for reaching out! To be honest, I haven't thoroughly tested how ViralMSA performs when it wraps around wfmash: I mainly wanted to make sure that all common read mappers I was aware of were integrated into that a user happens to be particularly interested in trying it out, so I thought adding support for wfmash would be a good idea!

Regarding the citation, here's the specific wfmash command ViralMSA uses:

```bash
wfmash -N --sam-format --threads=NUM_THREADS REF_GENOME SEQUENCES
```

So it sounds like adding the citation you listed makes sense! I'll add it to the code base, and it'll show up in the next ViralMSA release!
