### ISSUE TITLE
Replacing from subprocess import ... with import subprocess

### ISSUE THREAD

**Issue by daniel-ji** [niemasd/ViralMSA#26]
For WASM-friendliness / compatibility, if imported subprocess modules could be replaced with subprocess.module calls and `import subprocess` could be used instead of `from subprocess import ...`, that would be great. Thank you!

**Comment by niemasd** [comment]
Patched in https://github.com/niemasd/ViralMSA/commit/203d6eb6de5fffdb20c5f854446bcadacbbc14bd
