### ISSUE TITLE
Web app: Sample inputs

### ISSUE THREAD

**Issue by robertaboukhalil** [niemasd/ViralMSA#32]
Nice work on the web app!

Just a small suggestion to have a button that preloads an example `.fa` + reference input, for those of us who don't have those handy 🙂

**Comment by niemasd** [comment]
Ooo, that's a great idea! Thank you, @robertaboukhalil! @daniel-ji, can you try to add that feature? Maybe you can have this "example" button preload the example HIV dataset in the ViralMSA repo, and have it select the HIV-1 reference genome?

**Comment by daniel-ji** [comment]
Sounds good, I'll look to implement it. Thanks for the idea @robertaboukhalil!

**Comment by niemasd** [comment]
Thanks for implementing that so quickly, @daniel-ji!

Thanks again for the suggestion, @robertaboukhalil! Should be working now in ViralMSA v1.1.29

**Comment by robertaboukhalil** [comment]
🥳
