### ISSUE TITLE
Web: After completion, the dots after runtime keep accumulating

### ISSUE THREAD

**Issue by corneliusroemer** [niemasd/ViralMSA#33]
Just tried it out, nice!

One small bug: the dots after the runtime display keep growing after analysis is done (the dots after "seconds"):

<img width="1894" alt="image" src="https://user-images.githubusercontent.com/25161793/229819879-0cc135f6-2c92-4b4b-91d1-5af633c4362f.png">

**Comment by niemasd** [comment]
Thank you for catching that! @daniel-ji Can you take a look?

Not directly related to this, but I wonder if we should replace the `...` progress indicator with an in-place spinny progress indicator? To avoid potential graphical bugs in edge cases where the runtime might be extremely long

**Comment by daniel-ji** [comment]
Sounds good, I'll replace the loading dots with a spinning progress indicator.

**Comment by niemasd** [comment]
Thanks for implementing that so quickly, @daniel-ji!

corneliusroemer Should be fixed in ViralMSA v1.1.29! Thank you again for catching that! Please let us know if you run into any issues later on
