### ISSUE TITLE
ERROR: Output directory exists: /home/drk/fast-out

### ISSUE THREAD

**Issue by t-doggg** [niemasd/ViralMSA#37]
When I try to start ViralMSA there is always this error-message but I don't understand this. It is required to select a directory so what is the problem? Is the problem maybe in the Code or do I understand something wrong here.

Thanks for the Answer ;)

**Comment by niemasd** [comment]
I see you closed the ticket, so I assume you figured it out, but just in case, this message simply means that the output folder you specified already exists (so you either need to pick a different output folder, or you need to delete the existing one). This is a safety measure to avoid accidentally overwriting your data
