### ISSUE TITLE
Tag on Dockerhub

### ISSUE THREAD

**Issue by lecorguille** [niemasd/ViralMSA#49]
Hi,
Can you create a tag on Dockerhub with the version number?
We prefer targeting one version for reproducibility.

Thanks

And one day, can you consider packaging your tool for Bioconda?

**Comment by niemasd** [comment]
Re: DockerHub tags, sure, will do! I'll knock that out tomorrow or so

Re: Bioconda, I probably won't package ViralMSA in Bioconda since it's just a single script, and the read mappers it can use (namely Minimap2) are already on Bioconda. So in a conda environment, you should be able to just install the read mappers with conda/mamba, and then download the single ViralMSA script (you can even run it from whatever directory you download it into, e.g. `./ViralMSA.py` or `~/tools/ViralMSA.py` or whatever)

**Comment by niemasd** [comment]
Versioned Docker image added! I'll keep releasing versioned images for future updates as well

https://hub.docker.com/r/niemasd/viralmsa/tags

**Comment by lecorguille** [comment]
> Re: DockerHub tags, sure, will do! I'll knock that out tomorrow or so

Cool

> Re: Bioconda, I probably won't package ViralMSA in Bioconda since it's just a single script, and the read mappers it can use (namely Minimap2) are already on Bioconda. So in a conda environment, you should be able to just install the read mappers with conda/mamba, and then download the single ViralMSA script (you can even run it from whatever directory you download it into, e.g. ./ViralMSA.py or ~/tools/ViralMSA.py or whatever)

On our computing infrastructure, we aim to install the tol resquested by our users. That way, they don't have to deal with conda, ... and the set of tools is shared among them. 
Bioconda doesn't filter the contribution. With conda, you will also get a Docker container and a Singularity images for free thanks to BioContainer.

**Comment by lecorguille** [comment]
It seems that the biopython is missing in your Docker image

FYI, here is the Apptainer definition

```
Bootstrap: docker
From:  niemasd/viralmsa:1.1.34

%post
    ## From apt
    export DEBIAN_FRONTEND=noninteractive
    apt-get -qq update && apt-get -qq upgrade -y
    apt-get -qq install -y python3-biopython
    apt-get -qq clean && rm -rf /var/lib/apt/lists/*

%runscript
    exec "$@"

%test
    ViralMSA.py -h
```

**Comment by niemasd** [comment]
Ah, shoot, thanks for catching that! I think I hadn't tested it without a local reference genome (BioPython is used to pull the web reference). I'll update the Docker image and create a new versioned release

Re: Bioconda, I see; that makes sense! I had a bit of difficulty submitting another tool this past weekend, but that was a C++ tool, so maybe this one will be easier. I'll take a look and see

**Comment by niemasd** [comment]
Added BioPython to ViralMSA v1.1.35 image:

https://hub.docker.com/layers/niemasd/viralmsa/1.1.35/images/sha256-df5c151c19282cd4ce282f5127b7ac0a183937fad3b4c6e0621089fba567b463?context=explore

Working on adding ViralMSA to Bioconda:

https://github.com/bioconda/bioconda-recipes/pull/43369

**Comment by niemasd** [comment]
Bioconda recipe now passing all tests; hopefully it'll be reviewed and merged soon!

**Comment by niemasd** [comment]
And it's been merged! ViralMSA should now be on conda through Bioconda 😄 Thanks for the suggestions!
